USE 'NursingTest';
--database name and table name may need to be changed

INSERT INTO 'Schools' ('SchoolName') VALUES
('Albertus Magnus College, CT'),
('Asnuntuck Community College, CT'),
('Capital Community College, CT'),
('Central Connecticut State University, CT'),
('Connecticut College, CT'),
('Eastern Connecticut State University, CT'),
('Fairfield University, CT'),
('Gateway Community College, CT'),
('Goodwin College, CT'),
('Holy Apostles College and Seminary, CT'),
('Housatonic Community College, CT'),
('Lincoln College of New England Hartford, CT'),
('Lincoln College of New England Southington, CT'),
('Lincoln College of New England Suffield, CT'),
('Lyme Academy College of Fine Arts, CT'),
('Manchester Community College, CT'),
('Middlesex Community College, CT'),
('Mitchell College, CT'),
('Naugatuck Valley Community College, CT'),
('Northwestern Connecticut Community College, CT'),
('Norwalk Community College, CT'),
('Paier College of Art Inc, CT'),
('Post University, CT'),
('Quinebaug Valley Community College, CT'),
('Quinnipiac University, CT'),
('Sacred Heart University, CT'),
('Saint Joseph College, CT'),
('Sanford Brown College Farmington, CT'),
('Southern Connecticut State University, CT'),
("St Vincent's College, CT"),
('Three Rivers Community College, CT'),
('Trinity College, CT'),
('Tunxis Community College, CT'),
('United States Coast Guard Academy, CT'),
('University of Bridgeport, CT'),
('University of Connecticut, CT'),
('University of Connecticut Avery Point, CT'),
('University of Connecticut Stamford, CT'),
('University of Connecticut Tri Campus, CT'),
('University of Hartford, CT'),
('University of New Haven, CT'),
('University of Phoenix Fairfield County Campus, CT'),
('Wesleyan University, CT'),
('Western Connecticut State University, CT'),
('Yale University, CT'),
('Other');
